### ISSUE TITLE
Let the user know why their Entry was not submitted

### ISSUE THREAD

**Issue by syedfkabir** [badgateway/tt-app#50]
## Task

This is a follow up to https://github.com/badgateway/tt-app/pull/49 

You can now successfully submit an Entry, however if you do not have a Project selected, you'll get a console error. 

After some discussion with the Bad Gateway team:
The submit button should not be disabled
The user should be able to hit submit and see why their submission was not successful 
This can be done using the `required` keyword on a `<form>`, however we are currently not using one 
Update the component to now use a form

### Screenshot

<img width="1916" alt="Screen Shot 2022-10-20 at 12 53 54 PM" src="https://user-images.githubusercontent.com/31973147/197012509-8b559f7e-349c-40b0-b553-1d1059fc4dfc.png">

**Comment by ikbensiep** [comment]
If you're a Real Cool Guy, add a `required` attribute to the `<select>` and the browser will not submit until it contains a valid value (ie a user has selected an actual option)

**Comment by BeckyPollard** [comment]
Having some GitHub UI struggles, don't mind this open/close noise an attempt was made
